services:
  api:
    build:
      context: .
      dockerfile: src/A8A.Api/Dockerfile
    ports:
      - "40080:8080"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: ./src/A8A.Web
    ports:
      - "4200:80"
    environment:
      - API_SERVICE_URL=api:8080
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./src/A8A.Web:/app
